### ISSUE TITLE
How does it track changes in composer.lock

### ISSUE THREAD

**Issue by aftabnaveed** [SanderSander/composer-link#26]
This seems to an interesting utility as opposed to the https://github.com/franzliedke/studio. The problem with the `studio` is that that it will keep the reference of the local package path in `composer.lock` file.  This utility seems to fix that problem just by keeping the reference in the composer.lock file and linking the package in the background. 

My question is when I have completed my changes in the package and now its time to run `composer update vendor/package` will it update the hash and timestamp in composer.lock file?

**Comment by SanderSander** [comment]
> My question is when I have completed my changes in the package and now its time to run `composer update vendor/package` will it update the hash and timestamp in composer.lock file?

Yes it will, the goal of this plugin is to maintain normal behavior of composer when updating/installing packages

As example when I have `package/package` on version 1.0.0  and I link that package to a local directory when I run a full `composer update` it will just update that package as normal from 1.0.0 to 1.0.1 and update the lock file. After this whole process this plugin will link the directory back in.

**Comment by aftabnaveed** [comment]
This makes sense thank you.
