### ISSUE TITLE
Wildcard support

### ISSUE THREAD

**Issue by aftabnaveed** [SanderSander/composer-link#27]
I am wondering if there is a wildcard support for symlinking packages. Let's say I have a folder `php-packages/package1` and `php-packages/package2` it would be nice if i can just enter a command `composer link ../php-packages/*` and it link all the packages in that folder. Is it something possible?

**Comment by SanderSander** [comment]
This would be doable, I think it should be limited to 1 directory depth, and search all sub directories for packages.

**Comment by SanderSander** [comment]
This is now in the master branch :) and will be released in 0.3.0
