### ISSUE TITLE
--only-installed flag returns error

### ISSUE THREAD

**Issue by ouun** [SanderSander/composer-link#48]
This is really one of my most loved packages. Thank you so much for making life easier!

I am trying to symlink multiple (already installed) packages. And it works great if I do it one by one. But as by the documentation the following would be a possible shorthand: 

`composer link ../path/* --only-installed `

However that always returns the error:   `The "--only-installed" option does not exist.`

Kind regards,

Philipp

**Comment by SanderSander** [comment]
Nice to hear that you like the package :) thanks!

Could you run `composer global show sandersander/composer-link` or `composer show sandersander/composer-link` to see which version you have.

Version `0.2.x` doesn't support the option yet, and it was added in `0.3.x` 

The following should work on version 0.3

`composer link "../path/*" --only-installed`

**Comment by ouun** [comment]
Thanks a lot for getting back to me so fast, @SanderSander!
Yes, I missed that I have added `sandersander/composer-link` as a dev-dependency to the package. So that (v0.2) was called instead of the global package (v0.3).

Your hint helped a lot to figure that out. All good now. 👍🏼
