### ISSUE TITLE
Feature request: add a unlink-all command

### ISSUE THREAD

**Issue by tdwesten** [SanderSander/composer-link#62]
Hi There, 

I would love to have a `composer unlink --all` or `composer unlink-all` command to unlink multiple packages.

**Comment by SanderSander** [comment]
@tdwesten At the moment it's possible to unlink all packages with `composer unlink "../*"` but this will only unlink all packages from the targeted directory. 

But yeah I agree it would be nice to have a command that simply unlinks all packages wherever they came from.
