### ISSUE TITLE
Any chance of tagging a new release?

### ISSUE THREAD

**Issue by lkrms** [SanderSander/composer-link#66]
Thanks for your work on this extension--it's been a lifesaver more than once :)

I've been seeing implicit nullable deprecation notices from `sandersander/composer-link` in my composer output, which prompted me to check for updates. Very pleased that it's not been abandoned 🎉, but with no new release tags since August 2022, I haven't been seeing the benefits of your work since then.

I know I could drop my stability requirements and follow a branch, but (a) I try to avoid doing that, and (b) most users following your `README.md` are probably in the same boat.

Thank you again!

**Comment by SanderSander** [comment]
Yes coming tomorrow, I experienced a small issue which I want to resolve and I got the the day off tomorrow, so all the time to create the release.

**Comment by lkrms** [comment]
Amazing! Thank you 🙏🏻
